excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gentokozuma.github.io
baseurl: /newspalette
title: Welcome to
author: Gento Kozuma
description: newspalette - news tidbits and terrible drawings
paginate: 5
google_analystics:
