excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gentokozuma.github.io
baseurl: /newspalette
title: Welcome!
author: Gento Kozuma
description: newspalette - news tidbits and terrible drawings by Gento Kozuma
paginate: 5
google_analystics:
