excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://gentokozuma.github.io
baseurl: /newspalette
title: newspalette
author: Gento Kozuma
description: news tidbits and terrible drawings
paginate: 5
paginate_path:
google_analystics:
